# Generated by Django 4.2.4 on 2023-08-28 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0002_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_id',
            name='order_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
