# Generated by Django 4.2.4 on 2023-08-28 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0003_alter_order_id_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(blank=True)),
                ('Main_Database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='splitter.main_database')),
            ],
        ),
        migrations.DeleteModel(
            name='Order_ID',
        ),
    ]
