# Generated by Django 4.2.4 on 2023-08-29 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0004_order_data_delete_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_database',
            name='item_field',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
