# Generated by Django 4.2.4 on 2023-09-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0005_main_database_item_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_data',
            name='user_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
