# Generated by Django 4.2.4 on 2023-09-04 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0006_order_data_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_data',
            old_name='user_id',
            new_name='group_id',
        ),
    ]
